services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: filmdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      TZ: Europe/Istanbul
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d filmdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/filmdb
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: 1234
      PGDATABASE: filmdb
      AUTO_WARMUP: "0"
      TZ: Europe/Istanbul
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - models:/models
    restart: unless-stopped

volumes:
  pgdata:
  models:
